title: open-devsecops
description: 'From Classroom to Industry: Bridging the DevSecOps Knowledge Gap with Open, Practical Learning.'
theme: just-the-docs

url: https://open-devsecops.github.io

aux_links:
  Github: https://github.com/open-devsecops

callouts:
  important:
    title: Important
    color: green
  warning:
    title: Warning
    color: yellow
  info:
    title: Info
    color: blue
